version: '3'

services:
  sqlite3:
    container_name: sqlite3
    image:  keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./databases/:/db/
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped
